// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AuthService 认证服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Login 用户登录，验证账号密码并创建会话
 */
export function Login(req: $models.LoginRequest): $CancellablePromise<$models.LoginResponse> {
    return $Call.ByID(1859042971, req);
}

/**
 * Logout 用户登出，使会话令牌失效
 */
export function Logout(req: $models.LogoutRequest): $CancellablePromise<$models.LogoutResponse> {
    return $Call.ByID(2132906312, req);
}
