// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BatchService 批量执行服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateBatchTask 创建批量任务
 */
export function CreateBatchTask(req: $models.CreateBatchTaskRequest): $CancellablePromise<$models.BatchTaskResponse> {
    return $Call.ByID(2802474883, req);
}

/**
 * DeleteBatchTask 删除任务（若有活跃执行先停止）
 */
export function DeleteBatchTask(req: $models.DeleteBatchTaskRequest): $CancellablePromise<$models.DeleteBatchTaskResponse> {
    return $Call.ByID(3322633854, req);
}

/**
 * GetBatchTask 获取任务详情（含有序命令项）
 */
export function GetBatchTask(req: $models.GetBatchTaskRequest): $CancellablePromise<$models.BatchTaskResponse> {
    return $Call.ByID(4059844803, req);
}

/**
 * GetBatchTaskProgress 获取任务执行进度（前端轮询调用）
 */
export function GetBatchTaskProgress(req: $models.GetBatchTaskProgressRequest): $CancellablePromise<$models.BatchTaskProgressResponse> {
    return $Call.ByID(269952092, req);
}

/**
 * GetBatchTasks 获取任务列表（含命令数量）
 */
export function GetBatchTasks(req: $models.GetBatchTasksRequest): $CancellablePromise<$models.BatchTasksResponse> {
    return $Call.ByID(2687698192, req);
}

/**
 * StartBatchTask 异步启动任务执行，返回 runId
 */
export function StartBatchTask(req: $models.StartBatchTaskRequest): $CancellablePromise<$models.StartBatchTaskResponse> {
    return $Call.ByID(1537870031, req);
}

/**
 * StopBatchTask 停止执行（中断当前命令，剩余标记 skipped）
 */
export function StopBatchTask(req: $models.StopBatchTaskRequest): $CancellablePromise<$models.StopBatchTaskResponse> {
    return $Call.ByID(3558041991, req);
}

/**
 * UpdateBatchTask 更新批量任务（重建命令项；有活跃执行时拒绝）
 */
export function UpdateBatchTask(req: $models.UpdateBatchTaskRequest): $CancellablePromise<$models.BatchTaskResponse> {
    return $Call.ByID(3406325184, req);
}
