// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConnService 连接管理服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateConnection 创建连接
 */
export function CreateConnection(req: $models.CreateConnectionRequest): $CancellablePromise<$models.ConnectionResponse> {
    return $Call.ByID(3955296790, req);
}

/**
 * DeleteConnection 删除连接（被命令引用时阻止）
 */
export function DeleteConnection(req: $models.DeleteConnectionRequest): $CancellablePromise<$models.DeleteConnectionResponse> {
    return $Call.ByID(687941325, req);
}

/**
 * GetConnections 获取连接列表（可筛选类型，敏感字段脱敏）
 */
export function GetConnections(req: $models.GetConnectionsRequest): $CancellablePromise<$models.ConnectionsResponse> {
    return $Call.ByID(179136063, req);
}

/**
 * TestConnection 测试已保存的连接
 */
export function TestConnection(req: $models.TestConnectionRequest): $CancellablePromise<$models.TestConnectionResponse> {
    return $Call.ByID(3367349370, req);
}

/**
 * TestConnectionConfig 测试未保存的连接配置（编辑弹窗内直接测试）
 */
export function TestConnectionConfig(req: $models.TestConnectionConfigRequest): $CancellablePromise<$models.TestConnectionResponse> {
    return $Call.ByID(1792158932, req);
}

/**
 * UpdateConnection 修改连接（敏感字段留空 = 保持不变）
 */
export function UpdateConnection(req: $models.UpdateConnectionRequest): $CancellablePromise<$models.ConnectionResponse> {
    return $Call.ByID(282836087, req);
}
