// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DashboardService 首页仪表盘服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearExecutionLogs 清空执行记录（按筛选条件）
 */
export function ClearExecutionLogs(req: $models.ClearExecutionLogsRequest): $CancellablePromise<$models.ClearExecutionLogsResponse> {
    return $Call.ByID(1837685772, req);
}

/**
 * GetDashboardStats 获取首页统计数据
 */
export function GetDashboardStats(token: string): $CancellablePromise<$models.DashboardStats | null> {
    return $Call.ByID(3706261497, token);
}

/**
 * GetExecutionLogs 获取执行记录列表
 */
export function GetExecutionLogs(req: $models.GetExecutionLogsRequest): $CancellablePromise<$models.ExecutionLogsResponse> {
    return $Call.ByID(3732183115, req);
}

/**
 * GetVersion 返回应用版本号
 */
export function GetVersion(): $CancellablePromise<string> {
    return $Call.ByID(851399622);
}
