// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as tunnel$0 from "./tunnel/models.js";

/**
 * BatchTunnelFailure 批量创建中的失败项
 */
export interface BatchTunnelFailure {
    "name": string;
    "message": string;
}

/**
 * Connection 连接信息
 */
export interface Connection {
    "id": number;

    /**
     * 连接名称（唯一）
     */
    "name": string;

    /**
     * ssh
     */
    "type": string;
    "host": string;
    "port": number;

    /**
     * SSH 用户名
     */
    "username": string;

    /**
     * ssh: password | key
     */
    "authMethod": string;

    /**
     * 库中加密存储，返回时脱敏
     */
    "password": string;

    /**
     * 私钥 PEM 内容（加密存储）
     */
    "privateKey": string;
    "privateKeyPath": string;

    /**
     * 私钥口令（加密存储）
     */
    "passphrase": string;
    "remark": string;

    /**
     * 是否已设置密码/私钥（脱敏后用于前端展示）
     */
    "hasSecret": boolean;
    "createdAt": string;
    "updatedAt": string;
}

export interface ConnectionResponse {
    "success": boolean;
    "connection": Connection | null;
    "message": string;
}

export interface ConnectionsResponse {
    "success": boolean;
    "connections": Connection[] | null;
    "message": string;
}

export interface CreateConnectionRequest {
    "token": string;
    "name": string;
    "type": string;
    "host": string;
    "port": number;
    "username": string;
    "authMethod": string;
    "password": string;
    "privateKey": string;
    "privateKeyPath": string;
    "passphrase": string;
    "remark": string;
}

export interface CreateEnvironmentRequest {
    "token": string;
    "name": string;
    "key": string;
    "sortOrder": number;
}

/**
 * CreateTunnelItem 批量创建中的单条隧道配置
 */
export interface CreateTunnelItem {
    "name": string;

    /**
     * local | remote | dynamic
     */
    "type": string;
    "localHost": string;
    "localPort": number;
    "remoteHost": string;
    "remotePort": number;
    "groupName": string;
    "autoStart": boolean;
    "autoReconnect": boolean;
    "remark": string;
}

export interface CreateTunnelRequest {
    "token": string;
    "name": string;
    "connectionId": number;
    "type": string;
    "localHost": string;
    "localPort": number;
    "remoteHost": string;
    "remotePort": number;
    "groupName": string;
    "autoStart": boolean;
    "autoReconnect": boolean;
    "remark": string;
}

/**
 * CreateTunnelsRequest 批量创建请求
 */
export interface CreateTunnelsRequest {
    "token": string;
    "connectionId": number;
    "tunnels": CreateTunnelItem[] | null;

    /**
     * 创建后是否立即全部启动
     */
    "startAll": boolean;
}

/**
 * CreateTunnelsResponse 批量创建响应
 */
export interface CreateTunnelsResponse {
    "success": boolean;
    "created": Tunnel[] | null;
    "failed": BatchTunnelFailure[] | null;
    "message": string;
}

/**
 * CreateUserRequest 创建用户请求
 */
export interface CreateUserRequest {
    "token": string;
    "username": string;
    "password": string;
    "role": string;
}

export interface DeleteConnectionRequest {
    "token": string;
    "id": number;
}

export interface DeleteConnectionResponse {
    "success": boolean;
    "message": string;

    /**
     * 被命令引用时阻止删除
     */
    "blocked": boolean;

    /**
     * 引用该连接的命令数量
     */
    "refCount": number;
}

export interface DeleteEnvResponse {
    "success": boolean;
    "message": string;
    "deletedCount": number;
}

export interface DeleteEnvironmentRequest {
    "token": string;
    "id": number;

    /**
     * 删除时脚本迁移目标环境（不能等于自身；至少保留一个环境）
     */
    "targetId": number;
}

export interface DeleteScriptRequest {
    "token": string;
    "id": number;
}

export interface DeleteTunnelRequest {
    "token": string;
    "id": number;
}

export interface DeleteTunnelResponse {
    "success": boolean;
    "message": string;
    "blocked": boolean;
}

/**
 * DeleteUserRequest 删除用户请求
 */
export interface DeleteUserRequest {
    "token": string;
    "id": number;
}

/**
 * Environment 环境信息
 */
export interface Environment {
    "id": number;
    "name": string;

    /**
     * 英文 key，作脚本磁盘子目录名 data/scripts/{key}/
     */
    "key": string;
    "sortOrder": number;
    "createdAt": string;
}

export interface EnvironmentsResponse {
    "success": boolean;
    "environments": Environment[] | null;
    "message": string;
}

/**
 * ExportTunnelsRequest 导出请求
 */
export interface ExportTunnelsRequest {
    "token": string;
}

/**
 * ExportTunnelsResponse 导出响应
 */
export interface ExportTunnelsResponse {
    "success": boolean;
    "tunnels": TunnelExport[] | null;
    "message": string;
}

/**
 * 请求/响应类型
 */
export interface GetConnectionsRequest {
    "token": string;

    /**
     * 可空，筛选类型
     */
    "type": string;
}

export interface GetEnvironmentsRequest {
    "token": string;
}

/**
 * GetTunnelLogsRequest 获取隧道日志请求
 */
export interface GetTunnelLogsRequest {
    "token": string;
    "id": number;
}

/**
 * 请求/响应类型
 */
export interface GetTunnelsRequest {
    "token": string;

    /**
     * 可选，筛选指定 SSH 连接的隧道
     */
    "connectionId": number;
}

/**
 * ImportTunnelsRequest 导入请求
 */
export interface ImportTunnelsRequest {
    "token": string;
    "tunnels": TunnelExport[] | null;
}

/**
 * ImportTunnelsResponse 导入响应
 */
export interface ImportTunnelsResponse {
    "success": boolean;
    "created": Tunnel[] | null;
    "failed": BatchTunnelFailure[] | null;
    "message": string;
}

/**
 * 请求/响应类型
 */
export interface ListScriptsRequest {
    "token": string;
    "environmentId": number;
}

/**
 * LoginRequest 登录请求
 */
export interface LoginRequest {
    "username": string;
    "password": string;
}

/**
 * LoginResponse 登录响应
 */
export interface LoginResponse {
    "success": boolean;
    "message": string;
    "username": string;
    "token": string;
}

/**
 * LogoutRequest 登出请求
 */
export interface LogoutRequest {
    "token": string;
}

/**
 * LogoutResponse 登出响应
 */
export interface LogoutResponse {
    "success": boolean;
    "message": string;
}

export interface ReadScriptRequest {
    "token": string;
    "id": number;
}

export interface RunScriptRequest {
    "token": string;
    "id": number;
    "args": string;
}

export interface SaveScriptRequest {
    "token": string;

    /**
     * 0=新建
     */
    "id": number;
    "name": string;
    "type": string;
    "content": string;
    "environmentId": number;
    "remark": string;
}

/**
 * Script 脚本信息
 */
export interface Script {
    "id": number;

    /**
     * 脚本名（不含扩展名，同环境唯一）
     */
    "name": string;

    /**
     * bat | ps1 | sh
     */
    "type": string;
    "environmentId": number;

    /**
     * 所属环境 key（磁盘子目录名 data/scripts/{envKey}/）
     */
    "envKey": string;
    "remark": string;

    /**
     * 修改时间（unix 秒）
     */
    "ts": number;
    "size": number;
}

export interface ScriptContentResponse {
    "success": boolean;
    "name": string;
    "type": string;
    "content": string;
    "message": string;
}

export interface ScriptResponse {
    "success": boolean;
    "script": Script | null;
    "message": string;
}

/**
 * ScriptRunProgress 脚本执行进度（前端轮询）
 */
export interface ScriptRunProgress {
    "success": boolean;
    "done": boolean;
    "output": string;
    "exitError": string;
    "exitCode": number;
    "durationMs": number;
    "message": string;
}

export interface ScriptsResponse {
    "success": boolean;
    "scripts": Script[] | null;
    "message": string;
}

/**
 * 请求/响应类型
 */
export interface StartTunnelRequest {
    "token": string;
    "id": number;
}

export interface StopScriptRunRequest {
    "token": string;
    "id": number;
}

export interface StopTunnelRequest {
    "token": string;
    "id": number;
}

export interface TestConnectionConfigRequest {
    "token": string;
    "type": string;
    "host": string;
    "port": number;
    "username": string;
    "authMethod": string;
    "password": string;
    "privateKey": string;
    "privateKeyPath": string;
    "passphrase": string;
}

export interface TestConnectionRequest {
    "token": string;

    /**
     * >0 测试已保存连接
     */
    "id": number;
}

export interface TestConnectionResponse {
    "success": boolean;
    "message": string;
    "latencyMs": number;
}

/**
 * Tunnel 隧道信息
 */
export interface Tunnel {
    "id": number;
    "name": string;
    "connectionId": number;

    /**
     * JOIN 带出
     */
    "connectionName": string;

    /**
     * local | remote | dynamic
     */
    "type": string;
    "localHost": string;
    "localPort": number;
    "remoteHost": string;
    "remotePort": number;

    /**
     * 分组标签（空=未分组）
     */
    "groupName": string;
    "autoStart": boolean;
    "autoReconnect": boolean;
    "sortOrder": number;
    "remark": string;

    /**
     * 运行时状态（GetTunnels 时附带）
     */
    "running": boolean;
    "connections": number;
    "reconnecting": boolean;
    "error"?: string;
    "bytesIn": number;
    "bytesOut": number;
    "createdAt": string;
    "updatedAt": string;
}

/**
 * TunnelExport 导出的隧道配置项（按连接名引用，不含敏感信息）
 */
export interface TunnelExport {
    "name": string;
    "connectionName": string;
    "type": string;
    "localHost": string;
    "localPort": number;
    "remoteHost": string;
    "remotePort": number;
    "groupName": string;
    "autoStart": boolean;
    "autoReconnect": boolean;
    "remark": string;
}

/**
 * 按组启停请求
 */
export interface TunnelGroupRequest {
    "token": string;
    "groupName": string;
}

/**
 * TunnelLogsResponse 隧道日志响应
 */
export interface TunnelLogsResponse {
    "success": boolean;
    "logs": tunnel$0.LogEntry[] | null;
    "message": string;
}

export interface TunnelResponse {
    "success": boolean;
    "tunnel": Tunnel | null;
    "message": string;
}

export interface TunnelStatusResponse {
    "success": boolean;
    "message": string;
    "running": boolean;
}

export interface TunnelStatusesResponse {
    "success": boolean;
    "tunnels": Tunnel[] | null;
    "message": string;
}

/**
 * 顶部栏隧道状态摘要
 */
export interface TunnelSummaryRequest {
    "token": string;
}

export interface TunnelSummaryResponse {
    "success": boolean;
    "total": number;
    "running": number;
    "reconnecting": number;
    "message": string;
}

export interface TunnelsResponse {
    "success": boolean;
    "tunnels": Tunnel[] | null;
    "message": string;
}

export interface UpdateConnectionRequest {
    "token": string;
    "id": number;
    "name": string;
    "type": string;
    "host": string;
    "port": number;
    "username": string;
    "authMethod": string;
    "password": string;
    "privateKey": string;
    "privateKeyPath": string;
    "passphrase": string;
    "remark": string;
}

export interface UpdateEnvironmentRequest {
    "token": string;
    "id": number;
    "name": string;
    "key": string;
    "sortOrder": number;
}

export interface UpdateTunnelRequest {
    "token": string;
    "id": number;
    "name": string;
    "connectionId": number;
    "type": string;
    "localHost": string;
    "localPort": number;
    "remoteHost": string;
    "remotePort": number;
    "groupName": string;
    "autoStart": boolean;
    "autoReconnect": boolean;
    "remark": string;
}

/**
 * UpdateUserRequest 更新用户请求
 */
export interface UpdateUserRequest {
    "token": string;
    "id": number;
    "username": string;
    "role": string;
    "password": string;
}

/**
 * User 用户信息
 */
export interface User {
    "id": number;
    "username": string;
    "role": string;
    "created_at": string;
}

/**
 * UserListRequest 获取用户列表请求
 */
export interface UserListRequest {
    "token": string;
}

/**
 * UserListResponse 用户列表响应
 */
export interface UserListResponse {
    "success": boolean;
    "users": User[] | null;
    "message": string;
}

/**
 * UserResponse 通用用户操作响应
 */
export interface UserResponse {
    "success": boolean;
    "message": string;
}
