// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * OpsService 指令库服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateCommand 创建命令
 */
export function CreateCommand(req: $models.CreateCommandRequest): $CancellablePromise<$models.CommandResponse> {
    return $Call.ByID(1764103275, req);
}

/**
 * DeleteCommand 删除单个命令
 */
export function DeleteCommand(req: $models.DeleteCommandRequest): $CancellablePromise<$models.DeleteCommandResponse> {
    return $Call.ByID(3515730214, req);
}

/**
 * GetCommands 获取命令列表（可按环境筛选）
 */
export function GetCommands(req: $models.GetCommandsRequest): $CancellablePromise<$models.CommandsResponse> {
    return $Call.ByID(2761146040, req);
}

/**
 * GetInteractiveOutput 获取交互式命令的新输出（前端轮询调用）
 */
export function GetInteractiveOutput(req: $models.GetInteractiveOutputRequest): $CancellablePromise<$models.GetInteractiveOutputResponse> {
    return $Call.ByID(931591723, req);
}

/**
 * GetStreamOutput 获取流式执行的新输出（前端轮询调用）
 */
export function GetStreamOutput(req: $models.GetStreamOutputRequest): $CancellablePromise<$models.GetInteractiveOutputResponse> {
    return $Call.ByID(1061311635, req);
}

/**
 * ResizeTerminal 调整终端尺寸（xterm 前端窗口变化时同步到 PTY）
 */
export function ResizeTerminal(req: $models.ResizeTerminalRequest): $CancellablePromise<$models.ProcessResponse> {
    return $Call.ByID(439295370, req);
}

/**
 * RunCommand 执行非交互式命令
 */
export function RunCommand(req: $models.RunCommandRequest): $CancellablePromise<$models.RunCommandResponse> {
    return $Call.ByID(2201536516, req);
}

/**
 * SendInteractiveInput 向交互式命令发送输入
 */
export function SendInteractiveInput(req: $models.SendInteractiveInputRequest): $CancellablePromise<$models.InteractiveInputResponse> {
    return $Call.ByID(2563697660, req);
}

/**
 * SendStreamInput 向流式（会话模式）shell 发送输入
 */
export function SendStreamInput(req: $models.SendStreamInputRequest): $CancellablePromise<$models.InteractiveInputResponse> {
    return $Call.ByID(641294096, req);
}

/**
 * SetEventEmitter 注入事件发射器（main.go 在创建 app 后调用）
 */
export function SetEventEmitter(ee: $models.EventEmitter): $CancellablePromise<void> {
    return $Call.ByID(424246720, ee);
}

/**
 * Shutdown 应用退出时终止所有运行中的守护进程、交互式会话和流式执行
 * （Windows 下 Job Object 的 KILL_ON_JOB_CLOSE 也会兜底，这里显式清理更可靠）
 */
export function Shutdown(): $CancellablePromise<void> {
    return $Call.ByID(3825309856);
}

/**
 * StartDaemon 启动守护进程类型命令（后台运行）
 */
export function StartDaemon(req: $models.StartDaemonRequest): $CancellablePromise<$models.ProcessResponse> {
    return $Call.ByID(943401770, req);
}

/**
 * StartInteractive 启动交互式命令（带 stdin 管道，前端可发送输入和轮询输出）
 */
export function StartInteractive(req: $models.StartInteractiveRequest): $CancellablePromise<$models.ProcessResponse> {
    return $Call.ByID(3977199030, req);
}

/**
 * StartStream 启动非交互式命令的流式执行（管道捕获，无 60s 超时）
 */
export function StartStream(req: $models.StartStreamRequest): $CancellablePromise<$models.ProcessResponse> {
    return $Call.ByID(976704846, req);
}

/**
 * StopDaemon 停止守护进程类型命令（终止整个进程树）
 */
export function StopDaemon(req: $models.StopDaemonRequest): $CancellablePromise<$models.ProcessResponse> {
    return $Call.ByID(1075245250, req);
}

/**
 * StopInteractive 停止交互式命令
 */
export function StopInteractive(req: $models.StopInteractiveRequest): $CancellablePromise<$models.ProcessResponse> {
    return $Call.ByID(2404414878, req);
}

/**
 * StopStream 停止流式执行（终止整个进程树）
 */
export function StopStream(req: $models.StopStreamRequest): $CancellablePromise<$models.ProcessResponse> {
    return $Call.ByID(3119621702, req);
}

/**
 * UpdateCommand 修改命令
 */
export function UpdateCommand(req: $models.UpdateCommandRequest): $CancellablePromise<$models.CommandResponse> {
    return $Call.ByID(1206940436, req);
}
