// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ScriptsService 脚本库服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteScript 删除脚本（文件 + DB 记录）
 */
export function DeleteScript(req: $models.DeleteScriptRequest): $CancellablePromise<$models.ScriptResponse> {
    return $Call.ByID(552363678, req);
}

/**
 * GetScriptRunProgress 获取脚本执行进度（前端轮询）
 */
export function GetScriptRunProgress(req: $models.ReadScriptRequest): $CancellablePromise<$models.ScriptRunProgress> {
    return $Call.ByID(3313002313, req);
}

/**
 * ListScripts 扫描各环境子目录 data/scripts/{envKey}/ 并与 DB 合并返回脚本列表
 * 规则：以磁盘文件为准——DB 有记录但文件丢失 → 清理记录；
 *      文件存在但 DB 无记录 → 自动补录（便于用户手动放入脚本文件）。
 * 子目录名即环境 key；根目录遗留平铺文件兜底归入首个环境并迁移进子目录。
 */
export function ListScripts(req: $models.ListScriptsRequest): $CancellablePromise<$models.ScriptsResponse> {
    return $Call.ByID(1459905710, req);
}

/**
 * ReadScript 读取脚本内容（文件丢失 → 清理 DB 记录并报错）
 */
export function ReadScript(req: $models.ReadScriptRequest): $CancellablePromise<$models.ScriptContentResponse> {
    return $Call.ByID(978982749, req);
}

/**
 * RunScript 启动脚本执行（异步：立即返回，输出经 GetScriptRunProgress 轮询获取）
 */
export function RunScript(req: $models.RunScriptRequest): $CancellablePromise<$models.ScriptRunProgress> {
    return $Call.ByID(3001012760, req);
}

/**
 * SaveScript 新建（id=0）或保存脚本：覆盖文件 + 更新 DB
 */
export function SaveScript(req: $models.SaveScriptRequest): $CancellablePromise<$models.ScriptResponse> {
    return $Call.ByID(4035439156, req);
}

/**
 * StopScriptRun 停止执行中脚本
 */
export function StopScriptRun(req: $models.StopScriptRunRequest): $CancellablePromise<$models.ScriptRunProgress> {
    return $Call.ByID(4200316402, req);
}
