// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TunnelService 隧道管理服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateTunnel 创建隧道
 */
export function CreateTunnel(req: $models.CreateTunnelRequest): $CancellablePromise<$models.TunnelResponse> {
    return $Call.ByID(2086116060, req);
}

/**
 * CreateTunnels 批量创建隧道：同一 SSH 连接一次创建多条端口映射
 * 逐条校验（复用 validateTunnel），失败项收集到 Failed 不中断；StartAll=true 时创建成功后自动启动。
 */
export function CreateTunnels(req: $models.CreateTunnelsRequest): $CancellablePromise<$models.CreateTunnelsResponse> {
    return $Call.ByID(1827176829, req);
}

/**
 * DeleteTunnel 删除隧道（运行中先停止）
 */
export function DeleteTunnel(req: $models.DeleteTunnelRequest): $CancellablePromise<$models.DeleteTunnelResponse> {
    return $Call.ByID(1714495603, req);
}

/**
 * ExportTunnels 导出全部隧道配置（供备份/迁移）
 */
export function ExportTunnels(req: $models.ExportTunnelsRequest): $CancellablePromise<$models.ExportTunnelsResponse> {
    return $Call.ByID(4029383711, req);
}

/**
 * GetTunnelLogs 获取隧道运行日志（启动/停止/连接/重连/错误事件，最新在前）
 */
export function GetTunnelLogs(req: $models.GetTunnelLogsRequest): $CancellablePromise<$models.TunnelLogsResponse> {
    return $Call.ByID(2892805527, req);
}

/**
 * GetTunnelSummary 获取隧道状态摘要（顶部栏指示器用）
 * 轻量接口：只返回 total / running / reconnecting 计数，不返回完整列表
 */
export function GetTunnelSummary(req: $models.TunnelSummaryRequest): $CancellablePromise<$models.TunnelSummaryResponse> {
    return $Call.ByID(515618852, req);
}

/**
 * GetTunnels 获取隧道列表（可按连接筛选，附带运行时状态）
 */
export function GetTunnels(req: $models.GetTunnelsRequest): $CancellablePromise<$models.TunnelsResponse> {
    return $Call.ByID(3394420669, req);
}

/**
 * ImportTunnels 导入隧道配置（按连接名匹配 SSH 连接，逐条校验失败不中断）
 */
export function ImportTunnels(req: $models.ImportTunnelsRequest): $CancellablePromise<$models.ImportTunnelsResponse> {
    return $Call.ByID(1587679322, req);
}

/**
 * StartAllTunnels 启动所有隧道
 */
export function StartAllTunnels(req: $models.StartTunnelRequest): $CancellablePromise<$models.TunnelStatusesResponse> {
    return $Call.ByID(2118377212, req);
}

/**
 * StartTunnel 启动指定隧道
 */
export function StartTunnel(req: $models.StartTunnelRequest): $CancellablePromise<$models.TunnelStatusResponse> {
    return $Call.ByID(655280592, req);
}

/**
 * StartTunnelGroup 按分组启动隧道（组名为空=未分组）
 */
export function StartTunnelGroup(req: $models.TunnelGroupRequest): $CancellablePromise<$models.TunnelStatusesResponse> {
    return $Call.ByID(2771588755, req);
}

/**
 * StopAllTunnels 停止所有隧道
 */
export function StopAllTunnels(req: $models.StopTunnelRequest): $CancellablePromise<$models.TunnelStatusesResponse> {
    return $Call.ByID(3841006676, req);
}

/**
 * StopTunnel 停止指定隧道
 */
export function StopTunnel(req: $models.StopTunnelRequest): $CancellablePromise<$models.TunnelStatusResponse> {
    return $Call.ByID(3290292968, req);
}

/**
 * StopTunnelGroup 按分组停止隧道（组名为空=未分组）
 */
export function StopTunnelGroup(req: $models.TunnelGroupRequest): $CancellablePromise<$models.TunnelStatusesResponse> {
    return $Call.ByID(3544497899, req);
}

/**
 * UpdateTunnel 修改隧道
 */
export function UpdateTunnel(req: $models.UpdateTunnelRequest): $CancellablePromise<$models.TunnelResponse> {
    return $Call.ByID(2383910001, req);
}
