// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UserService 用户管理服务
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateUser 创建新用户
 */
export function CreateUser(req: $models.CreateUserRequest): $CancellablePromise<$models.UserResponse> {
    return $Call.ByID(505588132, req);
}

/**
 * DeleteUser 删除用户
 */
export function DeleteUser(req: $models.DeleteUserRequest): $CancellablePromise<$models.UserResponse> {
    return $Call.ByID(2766801359, req);
}

/**
 * GetUsers 获取所有用户列表
 */
export function GetUsers(req: $models.UserListRequest): $CancellablePromise<$models.UserListResponse> {
    return $Call.ByID(2200747519, req);
}

/**
 * UpdateUser 更新用户信息
 */
export function UpdateUser(req: $models.UpdateUserRequest): $CancellablePromise<$models.UserResponse> {
    return $Call.ByID(1332528369, req);
}
