// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LogEntry 隧道日志条目（环形缓冲，供日志面板展示）
 */
export interface LogEntry {
    "time": string;

    /**
     * info | warn | error
     */
    "level": string;
    "message": string;
}
