// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as server$0 from "../../../../../opsflash/server/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "pty:output": server$0.TerminalOutputEvent;
            "time": string;
        }
    }
}
