// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * QueryResult 一条指令/SQL 的结构化结果
 */
export interface QueryResult {
    "columns": string[] | null;
    "rows": (string[] | null)[] | null;

    /**
     * 非查询类语句影响行数
     */
    "affected": number;
    "durationMs": number;
}
